### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by dphilpot** [Oefenweb/ansible-snmpd#11]
Hi Oefenweb,

with the newest ansible version (2.0.1.0) we get a deprecation warning

example:
`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{snmpd_dependencies}}'). This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by tersmitten** [comment]
I don't really understand the warning. Is is about [this line](https://github.com/Oefenweb/ansible-snmpd/blob/acf0e34f969bb04b21063cad30e25015e536385c/tasks/main.yml#L9)?

**Comment by dphilpot** [comment]
Hi tersmitten,

its not only that line

found a second one

`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{snmpd_install}}'). This feature will be removed in a future
 release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

If i understand the warning correct ( https://docs.ansible.com/ansible/porting_guide_2.0.html )
it should be this one

> When specifying complex args as a variable, the variable must use the full jinja2 variable syntax (`{{var_name}}`) - bare variable names there are no longer accepted. In fact, even specifying args with variables has been deprecated, and will not be allowed in future versions:

So maybe you just need to put some {{}} around it. i can test this in a few Minutes at our stage environment.

**Comment by tersmitten** [comment]
OK, but that's not backwards compatible isn't it?

**Comment by dphilpot** [comment]
Nope, im unsure of it need to run some tests but i created a pull request for the current issue

**Comment by tersmitten** [comment]
Than we'll know it soon :-)

**Comment by tersmitten** [comment]
Fingers crossed

**Comment by dphilpot** [comment]
Hmm im not sure why the build is failing but i think it has something todo with how you check if it was successful ...?

**Comment by tersmitten** [comment]
Yes, it's the idempotence check that fail, what happens if you provision twice, does it tails you that something is changed?

**Comment by dphilpot** [comment]
nope work at my ansible version like it should. What exactly is this idempotence test?

**Comment by tersmitten** [comment]
Provisioning twice, expecting the second run to do (change) nothing

**Comment by dphilpot** [comment]
ah ok, didn't know that :D

So like i said the second and further runs don't change anything. So its quite stable at on my side
