### ISSUE TITLE
Why having default credentials?

### ISSUE THREAD

**Issue by thbar** [Oefenweb/ansible-snmpd#17]
Hello!

I'm just having a first look at the role, and wondering: why are there default passwords here https://github.com/Oefenweb/ansible-snmpd/blob/master/defaults/main.yml ?

Is that for CI to work, or is there another reason ?

Thanks!

**Comment by tersmitten** [comment]
Yes, it's for CI. 

But I'm open for improvements :-)

**Comment by thbar** [comment]
Thanks the for clarification! Ultimately browsing over the various implementations of roles for snmpd, I think I'll just roll my own ^_^. Closing this!
